BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "qcom-saha"
BBFILE_PATTERN_qcom-saha = "^${LAYERDIR}/"
BBFILE_PRIORITY_qcom-saha = "50"

LAYERVERSION_qcom-saha = "1"
LAYERSERIES_COMPAT_qcom-saha = "wrynose"

LAYERDEPENDS_qcom-saha = " \
    core \
    saha-common \
    qcom \
"
