BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "rockchip-saha"
BBFILE_PATTERN_rockchip-saha = "^${LAYERDIR}/"
BBFILE_PRIORITY_rockchip-saha = "50"
LAYERVERSION_rockchip-saha = "1"
LAYERSERIES_COMPAT_rockchip-saha = "wrynose"
LAYERDEPENDS_rockchip-saha = "core rockchip saha-microduck"
