PARTITION_LAYOUT_DIR = "tegra-saha-layout"
DEPENDS += "${PARTITION_LAYOUT_DIR}"
PARTITION_FILE:apollo-nx = "${STAGING_DATADIR}/${PARTITION_LAYOUT_DIR}/${PARTITION_LAYOUT_TEMPLATE}"
PARTITION_FILE_EXTERNAL:apollo-nx = "${STAGING_DATADIR}/${PARTITION_LAYOUT_DIR}/${PARTITION_LAYOUT_EXTERNAL}"
