#! /bin/bash

set -e

PROGNAME=$(basename $0)

usage()
{
    cat >&2 <<EOF
Usage: $PROGNAME --distro <DISTRO> [<options>]
Options:
    -h, --help         Print this usage message
    -d, --distro       Set the DISTRO name for newly created distro layer
    -c, --color        Colorize the output; can be 'never', 'always',
                             or 'auto' (default 'auto')
Arguments:
Examples:
- To create a new distro layer without mender configurations:
  $ $PROGNAME --distro testdistro
EOF
}

DISTRO_NAME=""

# get command line options
SHORTOPTS="hmd:"
LONGOPTS="help,distro:"

ARGS=$(getopt --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@" )
if [ $? != 0 ]; then
   usage
   exit 1
fi

eval set -- "$ARGS"
while true;
do
    case $1 in
        -h | --help)       usage; exit 0 ;;
        -d | --distro)     DISTRO_NAME="$2"; shift 2;;
        -- )               shift; break ;;
        * )                break ;;
    esac
done

if [ -z "$DISTRO_NAME" ]; then
    usage
    echo "ERROR: You must specify DISTRO." >&2
    exit 1
fi

TOP_DIR=$(dirname $(dirname $0))
TOP_DIR=$(readlink -f "$TOP_DIR")
LAYER_DIR="${TOP_DIR}/layers/meta-${DISTRO_NAME}"

if [ -d layers/meta-tegra-saha ]; then

    echo -n "Creating a distro layer based on meta-saha..."
    
    cp -a layers/meta-tegra-saha ${LAYER_DIR}

    # Delete saha recipes
    rm -rf ${LAYER_DIR}/recipes-*

    # Adjust the data in templates
    mv ${LAYER_DIR}/conf/template-tegra-saha ${LAYER_DIR}/conf/template-${DISTRO_NAME}
    rm -rf ${LAYER_DIR}/conf/template-tegra-saha

    # Adjust the data in conf/distro
    cat ${LAYER_DIR}/conf/distro/tegra-saha.conf > ${LAYER_DIR}/conf/distro/${DISTRO_NAME}.conf
    rm -rf ${LAYER_DIR}/conf/distro/tegra-saha.conf

    # Change Layer attributes from tegra-saha
    find ${LAYER_DIR} -type f -exec sed -i "s/tegra-saha/${DISTRO_NAME}/" {} \;

    echo "Done!"
else
    echo "Warning: layers/meta-tegra-saha not present" >&2
    echo "This script uses meta-tegra-saha as template"
    exit 1
fi
