DESCRIPTION = "Saha robot image for D-Robotics RDK X5"
LICENSE = "MIT"

require recipes-saha/images/saha-image-common.inc

CORE_IMAGE_BASE_INSTALL += "packagegroup-saha-rdk-x5-base"
CORE_IMAGE_BASE_INSTALL += "packagegroup-saha-rdk-x5-ros2"

# The raw CONFIG partition is generated by the RDK BSP layer.  Keep WIC's
# native image-tool dependencies, but omit the generic architecture bootloader
# dependencies: board NAND keeps the official bootloader, and the WIC image
# must not build or install a replacement.
IMAGE_FSTYPES:append = " wic.bz2"
WKS_FILE = "rdk-x5.wks.in"
WKS_FILE_DEPENDS = "${WKS_FILE_DEPENDS_DEFAULT} d-robotics-bootfiles"
