BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "saha-microduck"
BBFILE_PATTERN_saha-microduck = "^${LAYERDIR}/"
BBFILE_PRIORITY_saha-microduck = "41"
LAYERVERSION_saha-microduck = "1"
LAYERSERIES_COMPAT_saha-microduck = "wrynose"
LAYERDEPENDS_saha-microduck = "core saha-common multimedia-layer"
