DISTRO = "saha-rdk-x5"
DISTRO_NAME = "Saha project distro for D-Robotics RDK X5"
DISTRO_VERSION_BASE = "alpha-1.0"
DISTRO_VERSION = "${DISTRO_VERSION_BASE}-${DATE}"
DISTRO_CODENAME = "wrynose"
SDK_VENDOR = "-sahardsdk"
SDK_VERSION := "${DISTRO_VERSION}"

MAINTAINER = "Homalozoa <nx.tardis@gmail.com>"
TARGET_VENDOR = "-saha"
LOCALCONF_VERSION = "1"

DISTRO_VERSION[vardepsexclude] = "DATE"
SDK_VERSION[vardepsexclude] = "DATE"

SAHA_RDK_X5_DISTRO_FEATURES = "largefile opengl systemd pam vfat"
DISTRO_FEATURES ?= "${DISTRO_FEATURES_DEFAULTS} ${SAHA_RDK_X5_DISTRO_FEATURES}"

INIT_MANAGER = "systemd"

INHERIT += "uninative"

BB_SIGNATURE_HANDLER ?= "OEEquivHash"
BB_HASHSERVE ??= "auto"
