BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "allwinner-saha"
BBFILE_PATTERN_allwinner-saha = "^${LAYERDIR}/"
BBFILE_PRIORITY_allwinner-saha = "50"
LAYERVERSION_allwinner-saha = "1"
LAYERSERIES_COMPAT_allwinner-saha = "wrynose"
LAYERDEPENDS_allwinner-saha = "core allwinner saha-microduck"
